apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jiki
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-jiki@sha256:bbbed30226bdfffc47661c5de9141a3129b041d6b3a6a2f66cfec00232945ada
        name: my-nodejs
        resources: {}
status: {}
